spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/nexora
    username: postgres
    password: Ubed@818
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql

server:
  port: 8484
  servlet:
    context-path: /nexora

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME}
  api-key: ${CLOUDINARY_API_KEY}
  api-secret: ${CLOUDINARY_API_SECRET}
